### ISSUE TITLE
whats the config file?

### ISSUE THREAD

**Issue by Mahone** [jumormt/DeepWukong#1]
PYTHONPATH="." python src/joern/joern-parse.py -c <config file>
what file is <config file>?

**Comment by rimon15** [comment]
By default, I think it's config/dwk.yaml

**Comment by jumormt** [comment]
Yes, the default configuration is configs/dwk.yaml. As for joern, please kindly refer to [joern](https://github.com/ives-nx/dwk_preprocess/tree/main/joern_slicer/joern) to generate PDG.

**Comment by jumormt** [comment]
will reopen if needed
