### ISSUE TITLE
关于joern

### ISSUE THREAD

**Issue by Nero0113** [jumormt/DeepWukong#10]
您好，我装好了您链接中的旧版joern，但我发现里面没有joern-parse

**Comment by Nero0113** [comment]
解决了

**Comment by mcf20** [comment]
> 解决了
您好 想请教一下你 可否帮我配置一下该版本的joern，重金感谢！！！

**Comment by mcf20** [comment]
> 解决了

您好 请问是如何安装连接中的joern的 感谢！！
