### ISSUE TITLE
Need to add -o option for running joern-parse.py

### ISSUE THREAD

**Issue by rimon15** [jumormt/DeepWukong#2]
On line 26 of `joern-parse.py`, it should be:

`system(f"{joern} -o {out_path} {source_path}")`

(-o option is required for output files)

**Comment by Blackjacktao** [comment]
thanks，can you tell me Which version of joern are you using

**Comment by jumormt** [comment]
Please kindly refer to [joern](https://github.com/ives-nx/dwk_preprocess/tree/main/joern_slicer/joern) to generate PDG.

**Comment by jumormt** [comment]
will reopen if needed
