### ISSUE TITLE
joern-parse.py有问题

### ISSUE THREAD

**Issue by Stwsyburg** [jumormt/DeepWukong#4]
Failure: Could not parse command line options
不知道你们joern版本是什么 反正我用你们给的命令跑不出来不知道怎么回事 你们也不上传一下joern requeirement也没写joern的版本
想换数据集复现都没办法

**Comment by Stwsyburg** [comment]
ok 我已经复现了你们了悟空 换了我们的数据集效果很不错


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumormt/DeepWukong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月9日(星期二) 晚上9:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumormt/DeepWukong] joern-parse.py有问题 (Issue #4)





 
你好，我们用的老版本joern :-)

**Comment by jumormt** [comment]
好的 good to hear

**Comment by mcf20** [comment]
> ok 我已经复现了你们了悟空 换了我们的数据集效果很不错
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jumormt/DeepWukong" ***@***.***&gt;; 发送时间:&nbsp;2022年8月9日(星期二) 晚上9:23 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [jumormt/DeepWukong] joern-parse.py有问题 (Issue #4) 你好，我们用的老版本joern :-) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

大佬  请问该项目环境如何配置呢
