### ISSUE TITLE
该项目还有用到SVF吗？

### ISSUE THREAD

**Issue by Wangkxkx** [jumormt/DeepWukong#5]
在文章中您提到使用SVF来提取控制依赖和数据依赖生成PDG。查看您在github上公开的项目源码，readme.md中描述使用Joern生成PDG。想请教一下您在最终实现的时候是选择用joern生成PDG，那SVF您还有再用到吗？

**Comment by jumormt** [comment]
感谢您的关注。PDG也可以用SVF生成，不过实现起来比joern会更复杂，故这里用joern做示例。事实上Deepwukong不局限于PDG生成的工具亦或编程语言，开发者可以采用不同工具生成PDG分析不同语言的程序。
