### ISSUE TITLE
can not generate XFGs

### ISSUE THREAD

**Issue by bymavis** [jumormt/DeepWukong#6]
hi, I have met something wrong in generating XFGs. It seems that the function 'build_PDG' will return None. Neither nodes_path nor edges_path exists (in # Line 111.)

**Comment by HS2021GO** [comment]
同问，我也是在生成XFGs这里，对比给出的CWE119示例中缺少mainfest.xml，想请教下这个xml文件是怎么得来的呢？

**Comment by bymavis** [comment]
> 同问，我也是在生成XFGs这里，对比给出的CWE119示例中缺少mainfest.xml，想请教下这个xml文件是怎么得来的呢？

你有没有试过，用CWE119（有xml文件的）数据集，去生成XFGs。我的build_PDG输出仍为none。主要因为node.csv和edge.csv这两个文件不存在。感觉现在数据处理缺了一步。

**Comment by jumormt** [comment]
@bymavis XFG生成依赖joern生成的PDG(node.csv and edge.csv)文件。需要先build好[joern](https://github.com/ives-nx/dwk_preprocess/tree/main/joern_slicer/joern)，然后运行`PYTHONPATH="." python src/joern/joern-parse.py -c <config file>`生成所有代码的node.csv和edge.csv文件

**Comment by jumormt** [comment]
@HS2021GO manifest.xml我有提供在数据集内，记录了代码路径和ground truth

**Comment by HS2021GO** [comment]
> @HS2021GO manifest.xml我有提供在数据集内，记录了代码路径和ground truth
感谢回复，你给出的很详细，用你提供好的数据集可以复现出来，想请教下，如果换成我自己的数据集，里面是一些c/c++的漏洞代码片段的这种形式，我该怎么对应生成需要的xml文件呀？

**Comment by HS2021GO** [comment]
> > 同问，我也是在生成XFGs这里，对比给出的CWE119示例中缺少mainfest.xml，想请教下这个xml文件是怎么得来的呢？
> 
> 你有没有试过，用CWE119（有xml文件的）数据集，去生成XFGs。我的build_PDG输出仍为none。主要因为node.csv和edge.csv这两个文件不存在。感觉现在数据处理缺了一步。
就是按照作者说的，我这可以的

**Comment by HS2021GO** [comment]
> @jumormt  manifest.xml我有提供在数据集内，记录了代码路径和ground truth
感谢回复，你给出的很详细，用你提供好的数据集可以复现出来，想请教下，如果换成我自己的数据集，里面是一些c/c++的漏洞代码片段的这种形式，我该怎么对应生成需要的xml文件呀？

**Comment by jumormt** [comment]
@HS2021GO 换成自己的数据集需要自己构建xml文件或者根据你的label方式修改[getCodeIDtoPathDict](https://github.com/jumormt/DeepWukong/blob/master/src/data_generator.py#L234)

**Comment by bymavis** [comment]
> joern
感谢回复！！非常nice。我再来请教一下，您提供的joern版本，我可能是没有build成功，出现了这样的错误“Error: Could not find or load main class tools.parser.ParserMain”。是需要运行build.sh吗？

**Comment by jumormt** [comment]
> > joern
> > 感谢回复！！非常nice。我再来请教一下，您提供的joern版本，我可能是没有build成功，出现了这样的错误“Error: Could not find or load main class tools.parser.ParserMain”。是需要运行build.sh吗？

是的，如果预编译的binary无法使用需要再local重新编译

**Comment by HS2021GO** [comment]
> @jumormt  换成自己的数据集需要自己构建xml文件或者根据你的label方式修改[getCodeIDtoPathDict](https://github.com/jumormt/DeepWukong/blob/master/src/data_generator.py#L234)

大佬，我想请教下，您给出的数据集中，每个testcase中的shared/108中的的三个文件是起什么作用的呀，还有就是生成xml的方法可以指点一下吗？方便提供下生成的代码不，我刚接触，比较挺小白，万分感谢。

**Comment by bymavis** [comment]
> > > joern
> > > 感谢回复！！非常nice。我再来请教一下，您提供的joern版本，我可能是没有build成功，出现了这样的错误“Error: Could not find or load main class tools.parser.ParserMain”。是需要运行build.sh吗？
> 
> 是的，如果预编译的binary无法使用需要再local重新编译

解决了，我也是入门级小白，多谢大佬～～

**Comment by mcf20** [comment]
> > > > joern
> > > > 感谢回复！！非常nice。我再来请教一下，您提供的joern版本，我可能是没有build成功，出现了这样的错误“Error: Could not find or load main class tools.parser.ParserMain”。是需要运行build.sh吗？
> > 
> > 
> > 是的，如果预编译的binary无法使用需要再local重新编译
> 
> 解决了，我也是入门级小白，多谢大佬～～

您好 方便告诉我本项目中joern是如何搭建的呢  一直没搞明白  感谢！！！！大佬
